import type { RorleggerProject } from './types'

/** 8 demo-prosjekter: 2 per region. Fiktive anlegg. */
export const DEMO_RORLEGGER_PROJECTS: RorleggerProject[] = [
  {
    id: 'ror-ost-jessheim',
    name: 'Opprusting bad og våtrom — boligsameie Jessheim',
    region: 'ost',
    status: 'paaGaende',
    contractType: 'lopende',
    startDate: '2025-09-01',
    endDate: '2026-06-30',
    budgetNok: 1_850_000,
    actualNok: 920_000,
    customerOrSite: 'Jessheim Boligsameie AS',
    summary: 'Totalrenovering av tre bad, nye hovedstokk og vannmålere.',
    notes: 'Koordinering med elektriker uke 12.',
    attachments: [
      { id: 'a1', name: 'Rammeavtale_ror_2025.pdf', type: 'kontrakt', date: '2025-08-15' },
      { id: 'a2', name: 'Endringsordre_B2_tilleggsstikk.pdf', type: 'endringsordre', date: '2025-11-03' },
    ],
    financialDetail: {
      approvedBudgetNok: 1_850_000,
      accruedOrActualNok: 920_000,
      invoicedToDateNok: 880_000,
      committedNok: 280_000,
      paidOutNok: 760_000,
      forecastAtCompletionNok: 1_780_000,
      contingencyRemainingNok: 40_000,
      health: 'underRamme',
      lines: [
        { label: 'Rør, armatur og innstøp', budgetNok: 520_000, actualNok: 265_000 },
        { label: 'Egeninnsats (timer)', budgetNok: 1_000_000, actualNok: 485_000 },
        { label: 'Underentreprise (flis, tørr)', budgetNok: 230_000, actualNok: 120_000 },
        { label: 'Inntak, transport, rigg', budgetNok: 100_000, actualNok: 50_000 },
      ],
    },
  },
  {
    id: 'ror-ost-lillestrom',
    name: 'Bunnledninger og fettutskillere — næringseiendom Lillestrøm',
    region: 'ost',
    status: 'paaGaende',
    contractType: 'fastpris',
    startDate: '2025-11-01',
    endDate: '2026-03-15',
    budgetNok: 4_200_000,
    actualNok: 2_100_000,
    customerOrSite: 'Lillestrøm Næringspark',
    summary: 'Utomhus dimensjonering og kumforlegning mot eksisterende spillvann.',
    attachments: [
      { id: 'a3', name: 'Kontrakt_fastpris_LN2025.pdf', type: 'kontrakt', date: '2025-10-20' },
    ],
  },
  {
    id: 'ror-sor-arendal',
    name: 'Fjernvarme og hovedledning — nytt omsorgssenter Arendal',
    region: 'sor',
    status: 'paaGaende',
    contractType: 'fastpris',
    startDate: '2025-04-01',
    endDate: '2026-11-30',
    budgetNok: 12_500_000,
    actualNok: 7_800_000,
    customerOrSite: 'Arendal kommune / Helsebygg Sør',
    summary: 'Prefab føringsveier, kulvert og shuntløsning mot fjernvarmesentral.',
    attachments: [
      { id: 'a4', name: 'Hovedkontrakt_Arendal_omsorg.pdf', type: 'kontrakt', date: '2025-03-10' },
      { id: 'a5', name: 'EO_01_fordypet_kum.pdf', type: 'endringsordre', date: '2025-09-22' },
    ],
  },
  {
    id: 'ror-sor-kristiansand',
    name: 'Trykktesting og lekkasjesøk — landbruksanlegg Kristiansand',
    region: 'sor',
    status: 'avsluttet',
    contractType: 'lopende',
    startDate: '2024-06-01',
    endDate: '2024-09-30',
    budgetNok: 380_000,
    actualNok: 365_000,
    customerOrSite: 'Sørlandet Agrar Drift',
    summary: 'Fullført. Mindre kostnadsjustering på spyl og dokumentasjon.',
    attachments: [
      { id: 'a6', name: 'Sluttrapport_trykk_ltk.pdf', type: 'annet', date: '2024-10-01' },
    ],
  },
  {
    id: 'ror-vest-bergen',
    name: 'Bade- og dusjanlegg — leilighetsblokk Bergen sentrum',
    region: 'vest',
    status: 'paaGaende',
    contractType: 'lopende',
    startDate: '2025-01-10',
    endDate: '2026-04-20',
    budgetNok: 5_100_000,
    actualNok: 3_250_000,
    customerOrSite: 'Bergen Sentrum Utvikling',
    summary: '32 enheter, prefab stående og liggende, felles trykkstøtte per etasje.',
    attachments: [
      { id: 'a7', name: 'Entrepriseramme_BSU.pdf', type: 'kontrakt', date: '2024-12-05' },
      { id: 'a8', name: 'EO_vedlikehold_ventil_4etg.pdf', type: 'endringsordre', date: '2025-08-18' },
    ],
  },
  {
    id: 'ror-vest-sotra',
    name: 'Pumpe og spillvann — industripark Sotra',
    region: 'vest',
    status: 'avsluttet',
    contractType: 'fastpris',
    startDate: '2023-11-01',
    endDate: '2024-05-30',
    budgetNok: 2_950_000,
    actualNok: 2_900_000,
    customerOrSite: 'Sotra Industriservice',
    summary: 'Leveranse og idriftsettelse avheftet. Avvik innen 2 % av ramme.',
    attachments: [
      { id: 'a9', name: 'Kontrakt_pumpe_Sotra_signert.pdf', type: 'kontrakt', date: '2023-10-12' },
    ],
  },
  {
    id: 'ror-mn-trondheim',
    name: 'Sykehus- og bunnledninger — paviljong Trondheim',
    region: 'midtNord',
    status: 'paaGaende',
    contractType: 'lopende',
    startDate: '2025-02-15',
    endDate: '2026-10-01',
    budgetNok: 18_200_000,
    actualNok: 5_100_000,
    customerOrSite: 'Helse Midt RHF',
    summary: 'Medisinsk teknisk, romklasser og koordinert renovering i drift.',
    attachments: [
      { id: 'a10', name: 'Hovedentreprise_Trn_hovedledning.pdf', type: 'kontrakt', date: '2025-01-20' },
      { id: 'a11', name: 'EO_isolasjon_akutt_post.pdf', type: 'endringsordre', date: '2025-10-30' },
    ],
  },
  {
    id: 'ror-mn-lofoten',
    name: 'Varmtvannsberedere og stål- og kobberbytte — hotell Lofoten',
    region: 'midtNord',
    status: 'paaGaende',
    contractType: 'fastpris',
    startDate: '2025-05-01',
    endDate: '2025-12-20',
    budgetNok: 1_200_000,
    actualNok: 640_000,
    customerOrSite: 'Lofoten Hotelldrift AS',
    summary: 'Feriehus og hovedbygg, begrenget rigg, alt innom rom uten nattestopp hotell.',
    attachments: [
      { id: 'a12', name: 'Fastprisavtale_VVB_Lofoten.pdf', type: 'kontrakt', date: '2025-04-10' },
    ],
  },
]

export function getDemoProjectById(id: string): RorleggerProject | undefined {
  return DEMO_RORLEGGER_PROJECTS.find((p) => p.id === id)
}
